export const API_CONSTANTS = {
  API_URL: 'https://librivox.org/api/feed',
  AI_API_URL: 'https://ecopal-api.vercel.app',
  DEFAULT_PARAMS:
    '?format=json&fields{id,title,description,authors,language,url_text_source,copyright_year,num_sections,totaltime,totaltimesecs,coverart_jpg,genres}&extended=1&coverart=1',
};

export const GENRES = new Map<string, string>([
  ['Action & Adventure', 'Akcija i Avantura'],
  ['Action & Adventure Fiction', 'Akcija i Avantura Fikcija'],
  ['General Fiction', 'Opća Fikcija'],
  ['Animals & Nature', 'Životinje i Priroda'],
  ["Children's Fiction", 'Dječija Fikcija'],
  ['Myths, Legends & Fairy Tales', 'Mitovi, Legende i Bajke'],
  ['Family', 'Porodica'],
  ['General', 'Opšte'],
  ['Historical', 'Historijski'],
  ['Poetry', 'Poezija'],
  ['Religion', 'Religija'],
  ['School', 'Škola'],
  ['Short Works', 'Kratka Djela'],
  ['Arts', 'Umjetnost'],
  ['Reference', 'Referenca'],
  ['Historical Fiction', 'Historijska Fikcija'],
  ['Biography', 'Biografija'],
  ['Detective Fiction', 'Detektivska Fikcija'],
  ['Dramatic Readings', 'Dramatična Čitanja'],
  ['Epistolary Fiction', 'Epistolarna Fikcija'],
  // ['Erotica', 'Erotika'],
  // ["Travel", "Putovanja"],
  ['Fantastic Fiction', 'Fantastična Fikcija'],
  ['Horror & Supernatural Fiction', 'Horor i Natprirodna Fikcija'],
  ['Gothic Fiction', 'Gotička Fikcija'],
  ['Science Fiction', 'Naučna Fikcija'],
  ['Fantasy Fiction', 'Fantazijska Fikcija'],
  ['Fictional Biographies & Memoirs', 'Fikcionalne Biografije i Memoari'],
  ['Published before 1800', 'Objavljeno prije 1800'],
  // ["Published 1800–1900", "Objavljeno 1800–1900"],
  ['Published 1900 onward', 'Objavljeno 1900 nadalje'],
  ['Humorous Fiction', 'Humoristična Fikcija'],
  ['Literary Fiction', 'Književna Fikcija'],
  ['Nature & Animal Fiction', 'Fikcija o Prirodi i Životinjama'],
  ['Nautical & Marine Fiction', 'Nautička i Morska Fikcija'],
  ['Comedy', 'Komedija'],
  ['Satire', 'Satira'],
  ['Drama', 'Drama'],
  ['Tragedy', 'Tragedija'],
  ['Romance', 'Romansa'],
  ['Anthologies', 'Antologije'],
  ['Single Author', 'Jedan Autor'],
  ['Ballads', 'Balade'],
  ['Elegies & Odes', 'Elegije i Ode'],
  ['Epics', 'Epovi'],
  ['Free Verse', 'Slobodni Stih'],
  ['Lyric', 'Lirika'],
  ['Narratives', 'Narativi'],
  ['*Non-fiction', 'Nefikcija'],
  ['Sonnets', 'Soneti'],
  ['Christian Fiction', 'Kršćanska Fikcija'],
  ['Sagas', 'Sage'],
  ['Short Stories', 'Kratke Priče'],
  ['Single Author Collections', 'Zbirke Jednog Autora'],
  // ["Suspense, Espionage & Thrillers", "Napetost, Špijunaža i Trileri"],
  ['War & Military Fiction', 'Ratna i Vojna Fikcija'],
  ['Westerns', 'Vesterni'],
  // ["Non-fiction", "Nefikcija"],
  ['Animals', 'Životinje'],
  ['Art, Design & Architecture', 'Umjetnost, Dizajn i Arhitektura'],
  ['Bibles', 'Biblije'],
  ['Memoirs', 'Memoari'],
  ['Business & Economics', 'Biznis i Ekonomija'],
  ['Crafts & Hobbies', 'Zanati i Hobiji'],
  ['Education', 'Obrazovanje'],
  ['Language Learning', 'Učenje Jezika'],
  ['Essays', 'Eseji'],
  ['Health & Fitness', 'Zdravlje i Fitnes'],
  ['Antiquity', 'Antika'],
  // ["Middle Ages", "Srednji Vijek"],
  ['Early Modern', 'Rani Moderni Period'],
  ['Modern (19th C)', 'Moderni (19. vijek)'],
  ['Modern (20th C)', 'Moderni (20. vijek)'],
  ['Cooking', 'Kuhanje'],
  ['Gardening', 'Vrtlarstvo'],
  ['Humor', 'Humor'],
  ['Law', 'Pravo'],
  ['Letters', 'Pisma'],
  ['Literary Criticism', 'Književna Kritika'],
  ['Mathematics', 'Matematika'],
  ['Medical', 'Medicinski'],
  ['Music', 'Muzika'],
  ['Nature', 'Priroda'],
  ['Performing Arts', 'Izvođačke Umjetnosti'],
  ['Ancient', 'Antički'],
  ['Medieval', 'Srednjovjekovni'],
  ['Modern', 'Moderni'],
  ['Contemporary', 'Savremeni'],
  ['Atheism & Agnosticism', 'Ateizam i Agnosticizam'],
  ['Political Science', 'Političke Nauke'],
  ['Psychology', 'Psihologija'],
  // ["Astronomy", "Astronomija"],
  ['Chemistry', 'Hemija'],
  ['Earth Sciences', 'Zemaljske Nauke'],
  ['Life Sciences', 'Životne Nauke'],
  ['Self-Help', 'Samopomoć'],
  // ["Social Science", "Društvene Nauke"],
  // ["Sports", "Sportovi"],
  ['Transportation', 'Transport'],
  ['Travel & Geography', 'Putovanja i Geografija'],
  ['Exploration', 'Istraživanje'],
  ['True Crime', 'Istinski Zločini'],
  ['Writing & Linguistics', 'Pisanje i Lingvistika'],
  ['Asian Antiquity', 'Azijska Antika'],
]);

export const LANGUAGES = new Map<string, string>([
  ['English', 'Engleski'],
  ['Spanish', 'Španski'],
  ['French', 'Francuski'],
  ['German', 'Njemački'],
  ['Italian', 'Talijanski'],
  ['Portuguese', 'Portugalski'],
  ['Russian', 'Ruski'],
  ['Chinese', 'Kineski'],
  ['Japanese', 'Japanski'],
  ['Korean', 'Korejski'],
]);
